local M = {}

function M.apply(p, cfg)
  local hi = function(name, opts)
    vim.api.nvim_set_hl(0, name, opts)
  end

  -- telescope.nvim
  hi("TelescopeNormal",          { fg = p.fg_main, bg = p.bg_popup })
  hi("TelescopeBorder",          { fg = p.border, bg = p.bg_popup })
  hi("TelescopePromptNormal",    { fg = p.fg_main, bg = p.bg_alt })
  hi("TelescopePromptBorder",    { fg = p.border, bg = p.bg_alt })
  hi("TelescopePromptTitle",     { fg = p.fg_modeline, bg = p.bg_modeline, bold = true })
  hi("TelescopePromptCounter",   { fg = p.fg_dim, bg = p.bg_alt })
  hi("TelescopePromptPrefix",    { fg = p.keyword, bg = p.bg_alt })
  hi("TelescopeResultsNormal",   { fg = p.fg_main, bg = p.bg_popup })
  hi("TelescopeResultsBorder",   { fg = p.border, bg = p.bg_popup })
  hi("TelescopeResultsTitle",    { fg = p.fg_alt, bg = p.bg_popup })
  hi("TelescopePreviewNormal",   { fg = p.fg_main, bg = p.bg_popup })
  hi("TelescopePreviewBorder",   { fg = p.border, bg = p.bg_popup })
  hi("TelescopePreviewTitle",    { fg = p.fg_alt, bg = p.bg_popup })
  hi("TelescopeSelection",       { bg = p.bg_completion })
  hi("TelescopeSelectionCaret",  { fg = p.keyword, bg = p.bg_completion })
  hi("TelescopeMultiSelection",  { fg = p.magenta, bg = p.bg_completion })
  hi("TelescopeMatching",        { fg = p.yellow_warmer, bold = true })
  hi("TelescopePreviewLine",     { bg = p.bg_hl_line })

  -- nvim-cmp
  hi("CmpItemAbbr",             { fg = p.fg_main })
  hi("CmpItemAbbrDeprecated",   { fg = p.fg_dim, strikethrough = true })
  hi("CmpItemAbbrMatch",        { fg = p.keyword, bold = true })
  hi("CmpItemAbbrMatchFuzzy",   { fg = p.yellow_warmer })
  hi("CmpItemMenu",             { fg = p.fg_dim, italic = true })
  hi("CmpItemKindDefault",      { fg = p.fg_alt })
  hi("CmpItemKindText",         { fg = p.fg_main })
  hi("CmpItemKindMethod",       { fg = p.fnname })
  hi("CmpItemKindFunction",     { fg = p.fnname })
  hi("CmpItemKindConstructor",  { fg = p.type })
  hi("CmpItemKindField",        { fg = p.magenta_faint })
  hi("CmpItemKindVariable",     { fg = p.variable })
  hi("CmpItemKindClass",        { fg = p.type })
  hi("CmpItemKindInterface",    { fg = p.type })
  hi("CmpItemKindModule",       { fg = p.fg_alt })
  hi("CmpItemKindProperty",     { fg = p.magenta_faint })
  hi("CmpItemKindUnit",         { fg = p.constant })
  hi("CmpItemKindValue",        { fg = p.constant })
  hi("CmpItemKindEnum",         { fg = p.type })
  hi("CmpItemKindKeyword",      { fg = p.keyword })
  hi("CmpItemKindSnippet",      { fg = p.green_cooler })
  hi("CmpItemKindColor",        { fg = p.magenta })
  hi("CmpItemKindFile",         { fg = p.blue })
  hi("CmpItemKindReference",    { fg = p.cyan_warmer })
  hi("CmpItemKindFolder",       { fg = p.blue })
  hi("CmpItemKindEnumMember",   { fg = p.constant })
  hi("CmpItemKindConstant",     { fg = p.constant })
  hi("CmpItemKindStruct",       { fg = p.type })
  hi("CmpItemKindEvent",        { fg = p.yellow_cooler })
  hi("CmpItemKindOperator",     { fg = p.fg_main })
  hi("CmpItemKindTypeParameter",{ fg = p.type })

  -- indent-blankline v3 (ibl)
  hi("IblIndent",     { fg = p.bg_active })
  hi("IblScope",      { fg = p.fg_dim })
  hi("IblWhitespace", { fg = p.bg_alt })
  -- indent-blankline v2 (legacy)
  hi("IndentBlanklineChar",           { fg = p.bg_active })
  hi("IndentBlanklineContextChar",    { fg = p.fg_dim })
  hi("IndentBlanklineSpaceChar",      { fg = p.bg_alt })
  hi("IndentBlanklineSpaceCharBlankline", { fg = p.bg_alt })

  -- rainbow-delimiters.nvim
  hi("RainbowDelimiterYellow",  { fg = p.rainbow[1] })
  hi("RainbowDelimiterMagenta", { fg = p.rainbow[2] })
  hi("RainbowDelimiterBlue",    { fg = p.rainbow[3] })
  hi("RainbowDelimiterRed",     { fg = p.rainbow[4] })
  hi("RainbowDelimiterViolet",  { fg = p.rainbow[5] })
  hi("RainbowDelimiterGreen",   { fg = p.rainbow[6] })
  hi("RainbowDelimiterCyan",    { fg = p.rainbow[7] })

  -- nvim-tree
  hi("NvimTreeNormal",         { fg = p.fg_main, bg = p.bg_dim })
  hi("NvimTreeNormalNC",       { fg = p.fg_dim, bg = p.bg_dim })
  hi("NvimTreeRootFolder",     { fg = p.fg_alt, bold = true })
  hi("NvimTreeGitDirty",       { fg = p.yellow_warmer })
  hi("NvimTreeGitNew",         { fg = p.green })
  hi("NvimTreeGitDeleted",     { fg = p.red })
  hi("NvimTreeGitStaged",      { fg = p.green_cooler })
  hi("NvimTreeSpecialFile",    { fg = p.magenta_warm })
  hi("NvimTreeIndentMarker",   { fg = p.bg_active })
  hi("NvimTreeImageFile",      { fg = p.magenta })
  hi("NvimTreeSymlink",        { fg = p.cyan_warmer })
  hi("NvimTreeFolderName",     { fg = p.blue })
  hi("NvimTreeOpenedFolderName",{ fg = p.blue, bold = true })
  hi("NvimTreeEmptyFolderName",{ fg = p.fg_dim })
  hi("NvimTreeFolderIcon",     { fg = p.blue_warmer })
  hi("NvimTreeOpenedFile",     { fg = p.fg_main, bold = true })
  hi("NvimTreeWinSeparator",   { fg = p.border, bg = p.bg_dim })

  -- neo-tree.nvim
  hi("NeoTreeNormal",          { fg = p.fg_main, bg = p.bg_dim })
  hi("NeoTreeNormalNC",        { fg = p.fg_dim, bg = p.bg_dim })
  hi("NeoTreeDirectoryIcon",   { fg = p.blue_warmer })
  hi("NeoTreeDirectoryName",   { fg = p.blue })
  hi("NeoTreeFileName",        { fg = p.fg_main })
  hi("NeoTreeFileIcon",        { fg = p.fg_alt })
  hi("NeoTreeSymbolicLinkTarget", { fg = p.cyan_warmer })
  hi("NeoTreeGitAdded",        { fg = p.green })
  hi("NeoTreeGitConflict",     { fg = p.red_warmer })
  hi("NeoTreeGitDeleted",      { fg = p.red })
  hi("NeoTreeGitIgnored",      { fg = p.fg_dim })
  hi("NeoTreeGitModified",     { fg = p.yellow_warmer })
  hi("NeoTreeGitUnstaged",     { fg = p.yellow_warmer })
  hi("NeoTreeGitUntracked",    { fg = p.green_cooler })
  hi("NeoTreeGitStaged",       { fg = p.green_cooler })
  hi("NeoTreeWinSeparator",    { fg = p.border, bg = p.bg_dim })

  -- which-key.nvim
  hi("WhichKey",          { fg = p.cyan })
  hi("WhichKeyGroup",     { fg = p.magenta_warm })
  hi("WhichKeyDesc",      { fg = p.fg_main })
  hi("WhichKeySeparator", { fg = p.fg_dim })
  hi("WhichKeyValue",     { fg = p.fg_dim })
  hi("WhichKeyBorder",    { fg = p.border, bg = p.bg_popup })
  hi("WhichKeyNormal",    { bg = p.bg_popup })

  -- nvim-notify
  hi("NotifyERRORBorder", { fg = p.red })
  hi("NotifyWARNBorder",  { fg = p.yellow_warmer })
  hi("NotifyINFOBorder",  { fg = p.info })
  hi("NotifyDEBUGBorder",  { fg = p.fg_dim })
  hi("NotifyTRACEBorder", { fg = p.fg_alt })
  hi("NotifyERRORIcon",   { fg = p.red })
  hi("NotifyWARNIcon",    { fg = p.yellow_warmer })
  hi("NotifyINFOIcon",    { fg = p.info })
  hi("NotifyDEBUGIcon",   { fg = p.fg_dim })
  hi("NotifyTRACEIcon",   { fg = p.fg_alt })
  hi("NotifyERRORTitle",  { fg = p.red, bold = true })
  hi("NotifyWARNTitle",   { fg = p.yellow_warmer, bold = true })
  hi("NotifyINFOTitle",   { fg = p.info, bold = true })
  hi("NotifyDEBUGTitle",  { fg = p.fg_dim, bold = true })
  hi("NotifyTRACETitle",  { fg = p.fg_alt, bold = true })

  -- noice.nvim
  hi("NoiceCmdline",      { fg = p.fg_main, bg = p.bg_popup })
  hi("NoiceCmdlineIcon",  { fg = p.keyword })
  hi("NoiceCmdlinePopupBorder", { fg = p.border })
  hi("NoiceCmdlinePopupTitle",  { fg = p.fg_alt })
  hi("NoicePopupBorder",  { fg = p.border })
  hi("NoiceFormatConfirm",{ fg = p.fg_main, bg = p.bg_popup })
  hi("NoiceFormatConfirmDefault", { fg = p.keyword, bold = true })

  -- mini.nvim (mini.indentscope, mini.statusline, etc.)
  hi("MiniIndentscopeSymbol",    { fg = p.fg_dim })
  hi("MiniIndentscopePrefix",    { nocombine = true })
  hi("MiniStatuslineModeNormal", { fg = p.fg_modeline, bg = p.bg_modeline, bold = true })
  hi("MiniStatuslineModeInsert", { fg = p.bg_main, bg = p.green, bold = true })
  hi("MiniStatuslineModeVisual", { fg = p.bg_main, bg = p.magenta, bold = true })
  hi("MiniStatuslineModeReplace",{ fg = p.bg_main, bg = p.red, bold = true })
  hi("MiniStatuslineModeCommand",{ fg = p.bg_main, bg = p.yellow_warmer, bold = true })
  hi("MiniStatuslineModeOther",  { fg = p.bg_main, bg = p.cyan, bold = true })
  hi("MiniStatuslineFilename",   { fg = p.fg_main, bg = p.bg_modeline })
  hi("MiniStatuslineFileinfo",   { fg = p.fg_main, bg = p.bg_modeline })
  hi("MiniStatuslineDevinfo",    { fg = p.fg_alt, bg = p.bg_modeline })
  hi("MiniStatuslineInactive",   { fg = p.fg_dim, bg = p.bg_inactive })
  hi("MiniTablineCurrent",       { fg = p.fg_modeline, bg = p.bg_modeline, bold = true })
  hi("MiniTablineVisible",       { fg = p.fg_main, bg = p.bg_alt })
  hi("MiniTablineHidden",        { fg = p.fg_dim, bg = p.bg_inactive })
  hi("MiniTablineModifiedCurrent",  { fg = p.yellow_warmer, bg = p.bg_modeline, bold = true })
  hi("MiniTablineModifiedVisible",  { fg = p.yellow_warmer, bg = p.bg_alt })
  hi("MiniTablineModifiedHidden",   { fg = p.yellow_warmer, bg = p.bg_inactive })
  hi("MiniTablineFill",          { bg = p.bg_dim })
  hi("MiniTablineTabpagesection",{ fg = p.fg_modeline, bg = p.bg_modeline })
  hi("MiniJump",                 { fg = p.fg_main, bg = p.bg_yellow_intense })
  hi("MiniJump2dSpot",           { fg = p.yellow_warmer, bg = p.bg_popup, bold = true })
  hi("MiniJump2dSpotAhead",      { fg = p.cyan_warmer, bg = p.bg_popup })
  hi("MiniJump2dDim",            { fg = p.fg_dim })
  hi("MiniCursorword",           { bg = p.bg_hover })
  hi("MiniCursorwordCurrent",    { bg = p.bg_hover2 })
  hi("MiniDiffSignAdd",          { fg = p.green })
  hi("MiniDiffSignChange",       { fg = p.yellow_warmer })
  hi("MiniDiffSignDelete",       { fg = p.red })
  hi("MiniDiffOverAdd",          { fg = p.fg_added, bg = p.bg_added })
  hi("MiniDiffOverChange",       { fg = p.fg_changed, bg = p.bg_changed })
  hi("MiniDiffOverDelete",       { fg = p.fg_removed, bg = p.bg_removed })
  hi("MiniDiffOverContext",      { bg = p.bg_dim })
end

return M
